export const INCREASE_LOADING = 'INCREASE_LOADING';
export const DESCREASE_LOADING = 'DESCREASE_LOADING';

export const AUTH_LOGIN = 'AUTH_LOGIN';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
export const AUTH_ME = 'AUTH_ME';
export const AUTH_CHECK_LOGGED = 'AUTH_CHECK_LOGGED';

export const USER_REPORT = 'USER_REPORT';
export const USER_DETAIL= 'USER_DETAIL';

export const CATEGORY_REPORT = 'CATEGORY_REPORT';
export const CATEGORY_DETAIL= 'CATEGORY_DETAIL';

export const OCCURRENCE_REPORT = 'OCCURRENCE_REPORT';
export const OCCURRENCE_DETAIL = 'OCCURRENCE_DETAIL';
export const OCCURRENCE_EXPORT = 'OCCURRENCE_EXPORT';

export const PROFILE_REPORT = 'PROFILE_REPORT';
export const PROFILE_DETAIL= 'PROFILE_DETAIL';

export const KPI_REPORT = 'KPI_REPORT';
export const MAP_MARKERS = 'MAP_MARKERS';